export const environment = {
  production: true,
  apiUrl: 'https://harmoney-backend.onrender.com/api/v1',
  routes: {
    auth: {
      login: '/auth/login',
      register: '/auth/register',
      verifyOtp: '/auth/verify-otp/register',
      logout: '/auth/logout',
      refresh: '/auth/refresh-token',
      forgotPassword: '/auth/forgot-password',
      resetPassword: '/auth/reset-password',
      passwordReset: {
        initiate: '/auth/password-reset/initiate',
        verify: '/auth/password-reset/verify',
        resendOtp: '/auth/resend-otp/password-reset',
        finalize: '/auth/password-reset/finalize',
      },
    },
    users: {
      getAll: '/users',
      getById: 'users/{id}',
      create: 'users',
      update: 'users/{id}',
      delete: 'users/{id}',
      profile: 'users/profile',
    },
    employees: {
      getAll: '/employee',
      getById: '/employee/{id}',
      create: '/employee',
      update: '/employee/{id}',
      delete: '/employee/{id}',
      profile: '/employee/profile',
    },
    departments: {
      getAll: '/department',
      getById: '/department/{id}',
      create: '/department',
      update: '/department/{id}',
      delete: '/department/{id}',
    },
    leave: {
      annual: '/leave/annual',
      getAll: '/leave/annual',
      create: '/leave/annual',
      absence: '/leave/absence',
      absenceGetAll: '/leave/absence',
      absenceCreate: '/leave/absence',
      sick: '/leave/sick',
      sickGetAll: '/leave/sick',
      sickCreate: '/leave/sick',
    },
    files: {
      uploadSingle: '/upload/single',
      uploadMultiple: '/upload/multiple',
      uploadAll: '/upload/all',
      delete: '/upload/delete',
    },
    campMeeting: {
      getAll: '/camp-meeting',
    },
    analytics: {
      getAnalyticsOverview: '/analytics/overview',
      getLeaveStatistics: '/analytics/leave-stat',
      getEmployeeDemographics: '/analytics/employee-demographics',
    },
    appraisal: {
      create: '/appraisal',
      getAll: '/appraisal',
      getById: '/appraisal/{id}',
      update: '/appraisal/{id}',
      delete: '/appraisal/{id}',
    },
    promotion: {
      getAll: '/promotion',
      create: '/promotion',
      update: '/promotion/{id}',
      delete: '/promotion/{id}',
      approve: '/promotion/{id}',
      reject: '/promotion/{id}',
    },
    posts: {
      getAll: 'posts',
      getById: 'posts/{id}',
      create: 'posts',
      update: 'posts/{id}',
      delete: 'posts/{id}',
      getByUser: 'posts/user/{userId}',
    },
  },
};
