export const FORM_OPTIONS = {
  titles: ['Mr', 'Mrs', 'Ms', 'Dr', 'Prof'],
  genders: ['Male', 'Female', 'Other'],
  maritalStatuses: ['Single', 'Married', 'Divorced', 'Widowed', 'Separated'],
  yesNoOptions: ['Yes', 'No'],
  cities: [
    'Lagos',
    'Abuja',
    'Kano',
    'Ibadan',
    'Port Harcourt',
    'Benin City',
    'Maiduguri',
    'Zaria',
    'Aba',
    'Jos',
    'Ilorin',
    'Oyo',
    'Enugu',
    'Kaduna',
    'Kumo',
    'Ikeja',
    'Uyo',
    'Calabar',
    'Abeokuta',
    'Akure',
    'Bauchi',
    'Sokoto',
    'Onitsha',
    'Warri',
    'Okene',
    'Katsina',
    'Gombe',
    'Minna',
    'Yola',
    'Jalingo',
  ],
  states: [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Federal Capital Territory (FCT)',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
  ],
  countries: [
    'Nigeria',
    'Ghana',
    'South Africa',
    'Kenya',
    'United Kingdom',
    'United States',
    'Canada',
    'Germany',
    'France',
    'Netherlands',
    'Italy',
    'Spain',
    'Switzerland',
    'Belgium',
    'Australia',
    'Brazil',
    'India',
    'China',
    'Japan',
    'Others',
  ],
  leaveRequestTypes: [
    'Personal',
    'Sabbatical',
    'Family Emergency',
    'Medical',
    'Educational',
  ],
  leaveDurationUnits: ['Days', 'Weeks', 'Months', 'Years'],
};
